# Generated by Django 4.1.5 on 2024-03-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_event_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.ImageField(blank=True, default='./static/img/event_photos//default.jpg', null=True, upload_to='./static/img/event_photos/'),
        ),
    ]
